services:
  auth:
    build:
      context: ./auth
    ports:
      - "8080:8080"
    environment:
      - PROTO=http
      - HOST=localhost
      - PORT=:8080

  auth-ui:
    build:
      context: ./auth-ui
    ports:
      - "8081:80"

  prototype:
    build:
      context: ./prototype
    ports:
      - "8082:80"
