name: Auth CI

on: push
  # push:
  #   branches: [main]
  #   paths:
  #     - 'auth/**'
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - 'auth/**'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./auth
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go 1.25.0
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.0'
          # cache: true
          # cache-dependency-path: auth/go.sum

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v

      - name: Run tests
        run: go test -v ./...

  test:
    needs: check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./auth
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.0'
          # cache-dependency-path: auth/go.sum
      - run: go test ./... -v 



